version: '3'
services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - server.port=8081
      - SPRING_PROFILES_ACTIVE=product
      - module.config.user.address=http://user-service:8082
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - server.port=8082
      - SPRING_PROFILES_ACTIVE=user
    networks:
      - app-network

networks:
  app-network:
    driver: bridge